"""
PDF Report Generator Module for Finance Intel.

Generates monthly financial report as PDF.
Requires: pip install reportlab

Exports:
- generate_monthly_report_pdf(month, year, total_income, total_expense, total_savings)
  Returns PDF file as bytes for download.
"""

from io import BytesIO
from datetime import date

# Month names for display
MONTH_NAMES = [
    '', 'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
]


def _get_styles():
    """Load reportlab styles once."""
    from reportlab.lib.styles import getSampleStyleSheet
    return getSampleStyleSheet()


def _make_summary_table(total_income: float, total_expense: float, total_savings: float):
    """Build summary table for PDF."""
    from reportlab.platypus import Table, TableStyle
    from reportlab.lib import colors
    data = [
        ["Summary", "Amount (Rs)"],
        ["Total Income", "%.2f" % total_income],
        ["Total Expense", "%.2f" % total_expense],
        ["Total Savings", "%.2f" % total_savings],
    ]
    table = Table(data, colWidths=[200, 150])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
    ]))
    return table


def generate_monthly_report_pdf(month: int, year: int, total_income: float, total_expense: float, total_savings: float) -> bytes:
    """
    Create a simple PDF report with income, expense, savings.
    Returns PDF file as bytes.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
    except ImportError:
        raise ImportError("reportlab is not installed. Run: pip install reportlab")

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=50,
        leftMargin=50,
        topMargin=50,
        bottomMargin=50
    )
    styles = _get_styles()

    story = []
    story.append(Paragraph("Financial Report", styles['Heading1']))
    story.append(Spacer(1, 12))
    month_name = MONTH_NAMES[month] if 1 <= month <= 12 else str(month)
    story.append(Paragraph("%s %d" % (month_name, year), styles['Heading2']))
    story.append(Spacer(1, 24))

    table = _make_summary_table(total_income, total_expense, total_savings)
    story.append(table)
    story.append(Spacer(1, 24))
    story.append(Paragraph("Generated by Finance Intel - Personal Financial Intelligence System", styles['Normal']))
    story.append(Spacer(1, 12))
    story.append(Paragraph("This report includes total income, total expense and total savings for the selected month.", styles['Normal']))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()
